name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - pip
  - datashader
  - rasterio
#  - pip:                            # Packages installed from PyPI
#    - requests==2.21.0
